// ISO
export const ISO_3166_COUNTRY_CODES = [
  ["AD", "Andorra"],
  ["AE", "United Arab Emirates"],
  ["AF", "Afghanistan"],
  ["AG", "Antigua and Barbuda"],
  ["AI", "Anguilla"],
  ["AL", "Albania"],
  ["AM", "Armenia"],
  ["AO", "Angola"],
  ["AQ", "Antarctica"],
  ["AR", "Argentina"],
  ["AS", "American Samoa"],
  ["AT", "Austria"],
  ["AU", "Australia"],
  ["AW", "Aruba"],
  ["AX", "Åland Islands"],
  ["AZ", "Azerbaijan"],
  ["BA", "Bosnia and Herzegovina"],
  ["BB", "Barbados"],
  ["BD", "Bangladesh"],
  ["BE", "Belgium"],
  ["BF", "Burkina Faso"],
  ["BG", "Bulgaria"],
  ["BH", "Bahrain"],
  ["BI", "Burundi"],
  ["BJ", "Benin"],
  ["BL", "Saint Barthélemy"],
  ["BM", "Bermuda"],
  ["BN", "Brunei Darussalam"],
  ["BO", "Bolivia"],
  ["BQ", "Bonaire"],
  ["BR", "Brazil"],
  ["BS", "Bahamas"],
  ["BT", "Bhutan"],
  ["BV", "Bouvet Island"],
  ["BW", "Botswana"],
  ["BY", "Belarus"],
  ["BZ", "Belize"],
  ["CA", "Canada"],
  ["CC", "Cocos Islands"],
  ["CD", "Democratic Republic of the Congo"],
  ["CF", "Central African Republic"],
  ["CG", "Congo"],
  ["CH", "Switzerland"],
  ["CT", "Ivory Coast"],
  ["CK", "Cook Islands"],
  ["CL", "Chile"],
  ["CM", "Cameroon"],
  ["CN", "China"],
  ["CO", "Colombia"],
  ["CR", "Costa Rica"],
  ["CU", "Cuba"],
  ["CV", "Cabo Verde"],
  ["CW", "Curaçao"],
  ["CX", "Christmas Island"],
  ["CY", "Cyprus"],
  ["CZ", "Czech Republic"],
  ["DE", "Germany"],
  ["DJ", "Djibouti"],
  ["DK", "Denmark"],
  ["DM", "Dominica"],
  ["DO", "Dominican Republic"],
  ["DZ", "Algeria"],
  ["EC", "Ecuador"],
  ["EE", "Estonia"],
  ["EG", "Egypt"],
  ["EH", "Western Sahara"],
  ["ER", "Eritrea"],
  ["ES", "Spain"],
  ["ET", "Ethiopia"],
  ["FI", "Finland"],
  ["FJ", "Fiji"],
  ["FK", "Falkland Islands"],
  ["FM", "Mirconesia"],
  ["FO", "Faroe Islands"],
  ["FR", "France"],
  ["GA", "Gabon"],
  ["GB", "Great Britain"],
  ["GD", "Grenada"],
  ["GE", "Georgia"],
  ["GF", "French Guiana"],
  ["GG", "Guernsey"],
  ["GH", "Ghana"],
  ["GI", "Gibraltar"],
  ["GL", "Greenland"],
  ["GM", "Gambia"],
  ["GN", "Guinea"],
  ["GP", "Guadeloupe"],
  ["GQ", "Equatorial Guinea"],
  ["GR", "Greece"],
  ["GS", "South Georgia and the South Sandwich Islands"],
  ["GT", "Guatemala"],
  ["GU", "Guam"],
  ["GW", "Guinea-Bissau"],
  ["HK", "Hong Kong"],
  ["HM", "Heard Island and McDonald Islands"],
  ["HN", "Honduras"],
  ["HR", "Croatia"],
  ["HT", "Haiti"],
  ["HU", "Hungary"],
  ["ID", "Indonesia"],
  ["IE", "Ireland"],
  ["IL", "Israel"],
  ["IM", "Isle of Man"],
  ["IN", "India"],
  ["IO", "British Indian Ocean Territory"],
  ["IQ", "Iraq"],
  ["IR", "Iran"],
  ["IS", "Iceland"],
  ["IT", "Italy"],
  ["JE", "Jersey"],
  ["JM", "Jamaica"],
  ["JO", "Jordan"],
  ["JP", "Japan"],
  ["KE", "Kenya"],
  ["KG", "Kyrgyzstan"],
  ["KH", "Cambodia"],
  ["KI", "Kiribati"],
  ["KM", "Comoros"],
  ["KN", "Saint Kitts and Nevis"],
  ["KP", "North Korea"],
  ["KR", "South Korea"],
  ["KW", "Kuwait"],
  ["KY", "Cayman Islands"],
  ["KZ", "Kazakhstan"],
  ["LA", "Lao People's Democratic Republic"],
  ["LB", "Lebanon"],
  ["LC", "Saint Lucia"],
  ["LI", "Liechtenstein"],
  ["LK", "Sri Lanka"],
  ["LR", "Liberia"],
  ["LS", "Lesotho"],
  ["LT", "Lithuania"],
  ["LU", "Luxembourg"],
  ["LV", "Latvia"],
  ["LY", "Libya"],
  ["MA", "Morocco"],
  ["MC", "Monaco"],
  ["MD", "Moldova"],
  ["ME", "Montenegro"],
  ["MF", "Saint Martin"],
  ["MG", "Madagascar"],
  ["MH", "Marshall Islands"],
  ["MK", "North Macedonia"],
  ["ML", "Mali"],
  ["MM", "Myanmar"],
  ["MN", "Mongolia"],
  ["MO", "Macao"],
  ["MP", "Northern Marina Islands"],
  ["MQ", "Martinique"],
  ["MR", "Mauritania"],
  ["MS", "Montserrat"],
  ["MT", "Malta"],
  ["MU", "Mauritius"],
  ["MV", "Maldives"],
  ["MW", "Malawi"],
  ["MX", "Mexico"],
  ["MY", "Malaysia"],
  ["MZ", "Mozambique"],
  ["NA", "Namibia"],
  ["NC", "New Caledonia"],
  ["NE", "Niger"],
  ["NF", "Norfolk Island"],
  ["NG", "Nigeria"],
  ["NI", "Nicaragua"],
  ["NL", "Netherlands"],
  ["NO", "Norway"],
  ["NP", "Nepal"],
  ["NR", "Nauru"],
  ["NU", "Niue"],
  ["NZ", "New Zealand"],
  ["OM", "Oman"],
  ["PA", "Panama"],
  ["PE", "Peru"],
  ["PF", "French Polynesia"],
  ["PG", "Papua New Guinea"],
  ["PH", "Philippines"],
  ["PK", "Pakistan"],
  ["PL", "Poland"],
  ["PM", "Saint Pierre and Miquelon"],
  ["PN", "Pitcairn"],
  ["PR", "Puerto Rico"],
  ["PS", "Palestine"],
  ["PT", "Portugal"],
  ["PW", "Palau"],
  ["PY", "Paraguay"],
  ["QA", "Qatar"],
  ["RE", "Réunion"],
  ["RO", "Romania"],
  ["RS", "Serbia"],
  ["RU", "Russian Federation"],
  ["RW", "Rwanda"],
  ["SA", "Saudi Arabia"],
  ["SB", "Solomon Islands"],
  ["SC", "Seychelles"],
  ["SD", "Sudan"],
  ["SE", "Sweden"],
  ["SG", "Singapore"],
  ["SH", "Saint Helena"],
  ["SI", "Slovenia"],
  ["SJ", "Svalbard and Jan Mayen"],
  ["SK", "Slovakia"],
  ["SL", "Sierra Leone"],
  ["SM", "San Marino"],
  ["SN", "Senegal"],
  ["SO", "Somalia"],
  ["SR", "Suriname"],
  ["SS", "South Sudan"],
  ["ST", "Sao Tome and Principe"],
  ["SV", "El Salvador"],
  ["SX", "Sint Maarten"],
  ["SY", "Syrian Arab Republic"],
  ["SZ", "Eswatini"],
  ["TC", "Turks and Caicos"],
  ["TD", "Chad"],
  ["TF", "French Southern Territories"],
  ["TG", "Togo"],
  ["TH", "Thailand"],
  ["TJ", "Tajikistan"],
  ["TK", "Tokelau"],
  ["TL", "Timor-Leste"],
  ["TM", "Turkmenistan"],
  ["TN", "Tunisia"],
  ["TO", "Tonga"],
  ["TR", "Turkey"],
  ["TT", "Trinidad and Tobago"],
  ["TV", "Tuvalu"],
  ["TW", "Taiwan"],
  ["TZ", "Tanzania"],
  ["UA", "Ukraine"],
  ["UG", "Uganda"],
  ["UM", "United States Minor Outlying Islands"],
  ["US", "United States of America"],
  ["UY", "Uruguay"],
  ["UZ", "Uzbekistan"],
  ["VA", "Vatican City"],
  ["VC", "Saint Vincent and the Grenadines"],
  ["VE", "Venezuela"],
  ["VG", "British Virgin Islands"],
  ["VI", "US Virgin Islands"],
  ["VN", "Vietnam"],
  ["VU", "Vanuatu"],
  ["WF", "Wallis and Futuna"],
  ["WS", "Samoa"],
  ["YE", "Yemen"],
  ["YT", "Mayotte"],
  ["ZA", "South Africa"],
  ["ZM", "Zambia"],
  ["ZW", "Zimbabwe"]
];

export type ISO_3166_COUNTRY_CODE = typeof ISO_3166_COUNTRY_CODES[number][0];

export const ISO_639_LANGUAGE_CODES = [
  ["en", "English", "English", 1_500_000_000],
  ["zh", "Chinese", "中文", 1_200_000_000],
  ["hi", "Hindi", "हिन्दी", 600_000_000],
  ["es", "Spanish", "Español", 460_000_000],
  ["ar", "Arabic", "العربية", 310_000_000],
  ["bn", "Bengali", "বাংলা", 230_000_000],
  ["pt", "Portuguese", "Português", 230_000_000],
  ["ru", "Russian", "Русский", 154_000_000],
  ["ja", "Japanese", "日本語", 128_000_000],
  ["pa", "Punjabi", "ਪੰਜਾਬੀ", 125_000_000],
  ["mr", "Marathi", "मराठी", 83_000_000],
  ["jv", "Javanese", "ꦧꦱꦗꦮ", 82_000_000],
  ["fa", "Persian", "فارسی", 80_000_000],
  ["fr", "French", "Français", 77_000_000],
  ["ha", "Hausa", "Hausa", 77_000_000],
  ["ko", "Korean", "한국어", 77_000_000],
  ["de", "German", "Deutsch", 76_000_000],
  ["vi", "Vietnamese", "Tiếng Việt", 76_000_000],
  ["ta", "Tamil", "தமிழ்", 75_000_000],
  ["te", "Telugu", "తెలుగు", 75_000_000],
  ["tr", "Turkish", "Türkçe", 75_000_000],
  ["ur", "Urdu", "اردو", 68_000_000],
  ["it", "Italian", "Italiano", 67_000_000],
  ["gu", "Gujarati", "ગુજરાતી", 55_000_000],
  ["ps", "Pashto", "پښتو", 50_000_000],
  ["ig", "Igbo", "Igbo", 45_000_000],
  ["pl", "Polish", "Polski", 45_000_000],
  ["kn", "Kannada", "ಕನ್ನಡ", 44_000_000],
  ["id", "Indonesian", "Bahasa Indonesia", 43_000_000],
  ["su", "Sundanese", "Basa Sunda", 39_000_000],
  ["or", "Oriya", "ଓଡ଼ିଆ", 37_000_000],
  ["th", "Thai", "ไทย", 36_000_000],
  ["ml", "Malayalam", "മലയാളം", 35_000_000],
  ["am", "Amharic", "አማርኛ", 32_000_000],
  ["az", "Azerbaijani", "Azərbaycan dili", 32_000_000],
  ["my", "Burmese", "ဗမာစာ", 32_000_000],
  ["uk", "Ukrainian", "Українська", 32_000_000],
  ["uz", "Uzbek", "Oʻzbekcha", 32_000_000],
  ["ku", "Kurdish", "Kurdî", 30_000_000],
  ["tl", "Tagalog", "Tagalog", 28_000_000],
  ["zu", "Zulu", "isiZulu", 27_000_000],
  ["ff", "Fulah", "Pulaar", 25_000_000],
  ["mg", "Malagasy", "Malagasy", 25_000_000],
  ["om", "Oromo", "Afaan Oromoo", 24_000_000],
  ["ro", "Romanian", "Română", 24_000_000],
  ["sd", "Sindhi", "سنڌي", 24_000_000],
  ["as", "Assamese", "অসমীয়া", 23_000_000],
  ["nl", "Dutch", "Nederlands", 23_000_000],
  ["ms", "Malay", "Bahasa Melayu", 20_000_000],
  ["yo", "Yoruba", "Èdè Yorùbá", 20_000_000],
  ["xh", "Xhosa", "isiXhosa", 19_000_000],
  ["km", "Central Khmer", "ខ្មែរ", 16_000_000],
  ["ne", "Nepali", "नेपाली", 16_000_000],
  ["si", "Sinhala", "සිංහල", 16_000_000],
  ["so", "Somali", "Soomaali", 16_000_000],
  ["sw", "Swahili", "Kiswahili", 16_000_000],
  ["za", "Zhuang", "Cuengh", 16_000_000],
  ["bm", "Bambara", "Bamanankan", 14_000_000],
  ["el", "Greek", "Ελληνικά", 13_000_000],
  ["hu", "Hungarian", "Magyar", 13_000_000],
  ["ht", "Haitian", "Kreyòl Ayisyen", 12_000_000],
  ["kk", "Kazakh", "қазақ тілі", 12_000_000],
  ["ny", "Chichewa", "Chichewa", 12_000_000],
  ["rn", "Rundi", "Ikirundi", 12_000_000],
  ["rw", "Kinyarwanda", "Ikinyarwanda", 12_000_000],
  ["ak", "Akan", "Akan", 11_000_000],
  ["cs", "Czech", "Čeština", 10_700_000],
  ["ca", "Catalan", "Català", 10_000_000],
  ["ln", "Lingala", "Lingála", 10_000_000],
  ["sv", "Swedish", "Svenska", 10_000_000],
  ["ug", "Uighur", "ئۇيغۇرچە", 10_000_000],
  ["he", "Hebrew", "עברית", 9_000_000],
  ["sr", "Serbian", "Српски", 9_000_000],
  ["ti", "Tigrinya", "ትግርኛ", 9_000_000],
  ["tw", "Twi", "Twi", 9_000_000],
  ["tn", "Tswana", "Setswana", 8_200_000],
  ["bg", "Bulgarian", "Български", 8_000_000],
  ["qu", "Quechua", "Runasimi", 8_000_000],
  ["tg", "Tajik", "тоҷикӣ", 8_000_000],
  ["be", "Belarusian", "Беларуская", 7_600_000],
  ["sn", "Shona", "chiShona", 7_500_000],
  ["sq", "Albanian", "Shqip", 7_500_000],
  ["af", "Afrikaans", "Afrikaans", 7_200_000],
  ["ee", "Ewe", "Eʋegbe", 7_000_000],
  ["kg", "Kongo", "Kikongo", 7_000_000],
  ["ks", "Kashmiri", "कॉशुर", 7_000_000],
  ["lg", "Ganda", "Luganda", 7_000_000],
  ["lo", "Lao", "ລາວ", 7_000_000],
  ["tk", "Turkmen", "Türkmençe", 7_000_000],
  ["hy", "Armenian", "Հայերեն", 6_700_000],
  ["ki", "Kikuyu", "Gĩkũyũ", 6_600_000],
  ["st", "Southern Sotho", "Sesotho", 6_000_000],
  ["hr", "Croatian", "Hrvatski", 5_600_000],
  ["da", "Danish", "Dansk", 5_500_000],
  ["sk", "Slovak", "Slovenčina", 5_500_000],
  ["fi", "Finnish", "Suomi", 5_400_000],
  ["nb", "Norwegian Bokmål", "Bokmål", 5_300_000],
  ["no", "Norwegian", "Norsk", 5_300_000],
  ["tt", "Tatar", "татар теле", 5_200_000],
  ["mn", "Mongolian", "Монгол", 5_000_000],
  ["wo", "Wolof", "Wolof", 5_000_000],
  ["gn", "Guarani", "Avañe'ẽ", 4_850_000],
  ["ky", "Kirghiz", "кыргыз тили", 4_500_000],
  ["kr", "Kanuri", "Kanuri", 4_000_000],
  ["ka", "Georgian", "ქართული", 3_700_000],
  ["ts", "Tsonga", "Xitsonga", 3_700_000],
  ["lt", "Lithuanian", "Lietuvių", 3_000_000],
  ["mk", "Macedonian", "Македонски", 2_500_000],
  ["sl", "Slovenian", "Slovenščina", 2_500_000],
  ["gl", "Galician", "Galego", 2_400_000],
  ["ss", "Swati", "siSwati", 2_300_000],
  ["ay", "Aymara", "Aymar aru", 2_200_000],
  ["bs", "Bosnian", "Bosanski", 2_200_000],
  ["eo", "Esperanto", "Esperanto", 2_000_000],
  ["ii", "Sichuan Yi", "ꆈꌠꉙ", 2_000_000],
  ["nd", "North Ndebele", "isiNdebele", 2_000_000],
  ["oc", "Occitan", "Occitan", 2_000_000],
  ["ve", "Venda", "Tshivenda", 1_700_000],
  ["li", "Limburgan", "Limburgs", 1_600_000],
  ["aa", "Afar", "Qafár af", 1_500_000],
  ["ce", "Chechen", "Нохчийн", 1_500_000],
  ["lu", "Luba-Katanga", "Tshiluba", 1_500_000],
  ["lv", "Latvian", "Latviešu", 1_500_000],
  ["sc", "Sardinian", "Sardu", 1_500_000],
  ["yi", "Yiddish", "ייִדיש", 1_500_000],
  ["ba", "Bashkir", "Башҡорт теле", 1_400_000],
  ["bo", "Tibetan", "བོད་ཡིག", 1_300_000],
  ["ga", "Irish", "Gaeilge", 1_200_000],
  ["cv", "Chuvash", "Чӑвашла", 1_100_000],
  ["et", "Estonian", "Eesti", 1_100_000],
  ["nr", "South Ndebele", "isiNdebele", 1_100_000],
  ["ng", "Ndonga", "Oshindonga", 1_000_000],
  ["av", "Avaric", "МагӀарул мацӀ", 760_000],
  ["eu", "Basque", "Euskara", 750_000],
  ["nn", "Norwegian Nynorsk", "Nynorsk", 750_000],
  ["cy", "Welsh", "Cymraeg", 740_000],
  ["os", "Ossetian", "Ирон", 700_000],
  ["wa", "Walloon", "Walon", 600_000],
  ["sg", "Sango", "Sängö", 550_000],
  ["mt", "Maltese", "Malti", 520_000],
  ["sm", "Samoan", "Gagana Samoa", 510_000],
  ["fy", "Western Frisian", "Frysk", 470_000],
  ["lb", "Luxembourgish", "Lëtzebuergesch", 400_000],
  ["dv", "Divehi", "ދިވެހި", 340_000],
  ["fj", "Fijian", "Na Vosa Vakaviti", 340_000],
  ["is", "Icelandic", "Íslenska", 330_000],
  ["hz", "Herero", "Otjiherero", 250_000],
  ["kj", "Kuanyama", "Kuanyama", 250_000],
  ["kv", "Komi", "Коми кыв", 220_000],
  ["br", "Breton", "Brezhoneg", 210_000],
  ["dz", "Dzongkha", "རྫོང་ཁ", 200_000],
  ["ab", "Abkhazian", "Аҧсуа", 190_000],
  ["to", "Tonga", "lea faka-Tonga", 187_000],
  ["nv", "Navajo", "Diné Bizaad", 170_000],
  ["mi", "Maori", "Te Reo Māori", 160_000],
  ["co", "Corsican", "Corsu", 150_000],
  ["ty", "Tahitian", "Reo Tahiti", 125_000],
  ["ho", "Hiri Motu", "Hiri Motu", 120_000],
  ["cr", "Cree", "ᓀᐦᐃᔭᐍᐏᐣ", 117_000],
  ["fo", "Faroese", "Føroyskt", 72_000],
  ["ch", "Chamorro", "Chamoru", 65_000],
  ["gd", "Gaelic", "Gàidhlig", 60_000],
  ["rm", "Romansh", "Rumantsch", 60_000],
  ["mh", "Marshallese", "Kajin M̧ajeļ", 58_000],
  ["kl", "Kalaallisut", "Kalaallisut", 57_000],
  ["oj", "Ojibwa", "ᐊᓂᔑᓈᐯᒧᐎᓐ", 50_000],
  ["iu", "Inuktitut", "ᐃᓄᒃᑎᑐᑦ", 39_000],
  ["se", "Northern Sami", "Davvisámegiella", 30_000],
  ["sa", "Sanskrit", "संस्कृतम्", 25_000],
  ["an", "Aragonese", "Aragonés", 10_000],
  ["bi", "Bislama", "Bislama", 10_000],
  ["na", "Nauru", "Dorerin Naoero", 10_000],
  ["ik", "Inupiaq", "Iñupiatun", 2_000],
  ["gv", "Manx", "Gaelg", 1_800],
  ["kw", "Cornish", "Kernowek", 500],
  ["io", "Ido", "Ido", 100],
  ["ae", "Avestan", "Avesta", 0],
  ["cu", "Church Slavonic", "Церковнославянский", 0],
  ["ia", "Interlingua", "Interlingua", 0],
  ["ie", "Interlingue", "Interlingue", 0],
  ["la", "Latin", "Latina", 0],
  ["pi", "Pali", "Pāli", 0],
  ["vo", "Volapük", "Volapük", 0]
];

export interface LanguageSetting {
  code: ISO_639_LANGUAGE_CODE;
  display: string;
}

export type ISO_639_LANGUAGE_CODE = typeof ISO_639_LANGUAGE_CODES[number][0];

export type ISO_15897_LOCALE_CODE = `${ISO_639_LANGUAGE_CODE}-${ISO_3166_COUNTRY_CODE}`;


// BLENDIN LEGACY
export type BlendinLocaleCode = ISO_15897_LOCALE_CODE | ISO_639_LANGUAGE_CODE;

export const ISO_4217_CURRENCY_CODES = [
  ["AED", "United Arab Emirates dirham"],
  ["AFN", "Afghan afghani"],
  ["ALL", "Albanian lek"],
  ["AMD", "Armenian dram"],
  ["ANG", "Netherlands Antillean guilder"],
  ["AOA", "Angolan kwanza"],
  ["ARS", "Argentine peso"],
  ["AUD", "Australian dollar"],
  ["AWG", "Aruban florin"],
  ["AZN", "Azerbaijani manat"],
  ["BAM", "Bosnia and Herzegovina convertible mark"],
  ["BBD", "Barbados dollar"],
  ["BDT", "Bangladeshi taka"],
  ["BGN", "Bulgarian lev"],
  ["BHD", "Bahraini dinar"],
  ["BIF", "Burundian franc"],
  ["BMD", "Bermudian dollar"],
  ["BND", "Brunei dollar"],
  ["BOB", "Boliviano"],
  ["BOV", "Bolivian Mvdol (funds code)"],
  ["BRL", "Brazilian real"],
  ["BSD", "Bahamian dollar"],
  ["BTN", "Bhutanese ngultrum"],
  ["BWP", "Botswana pula"],
  ["BYN", "Belarusian ruble"],
  ["BZD", "Belize dollar"],
  ["CAD", "Canadian dollar"],
  ["CDF", "Congolese franc"],
  ["CHE", "WIR euro (complementary currency)"],
  ["CHF", "Swiss franc"],
  ["CHW", "WIR franc (complementary currency)"],
  ["CLF", "Unidad de Fomento (funds code)"],
  ["CLP", "Chilean peso"],
  ["CNY", "Renminbi"],
  ["COP", "Colombian peso"],
  ["COU", "Unidad de Valor Real (UVR) (funds code)"],
  ["CRC", "Costa Rican colon"],
  ["CUP", "Cuban peso"],
  ["CVE", "Cape Verdean escudo"],
  ["CZK", "Czech koruna"],
  ["DJF", "Djiboutian franc"],
  ["DKK", "Danish krone"],
  ["DOP", "Dominican peso"],
  ["DZD", "Algerian dinar"],
  ["EGP", "Egyptian pound"],
  ["ERN", "Eritrean nakfa"],
  ["ETB", "Ethiopian birr"],
  ["EUR", "Euro"],
  ["FJD", "Fiji dollar"],
  ["FKP", "Falkland Islands pound"],
  ["GBP", "Pound sterling"],
  ["GEL", "Georgian lari"],
  ["GHS", "Ghanaian cedi"],
  ["GIP", "Gibraltar pound"],
  ["GMD", "Gambian dalasi"],
  ["GNF", "Guinean franc"],
  ["GTQ", "Guatemalan quetzal"],
  ["GYD", "Guyanese dollar"],
  ["HKD", "Hong Kong dollar"],
  ["HNL", "Honduran lempira"],
  ["HTG", "Haitian gourde"],
  ["HUF", "Hungarian forint"],
  ["IDR", "Indonesian rupiah"],
  ["ILS", "Israeli new shekel"],
  ["INR", "Indian rupee"],
  ["IQD", "Iraqi dinar"],
  ["IRR", "Iranian rial"],
  ["ISK", "Icelandic króna"],
  ["JMD", "Jamaican dollar"],
  ["JOD", "Jordanian dinar"],
  ["JPY", "Japanese yen"],
  ["KES", "Kenyan shilling"],
  ["KGS", "Kyrgyzstani som"],
  ["KHR", "Cambodian riel"],
  ["KMF", "Comoro franc"],
  ["KPW", "North Korean won"],
  ["KRW", "South Korean won"],
  ["KWD", "Kuwaiti dinar"],
  ["KYD", "Cayman Islands dollar"],
  ["KZT", "Kazakhstani tenge"],
  ["LAK", "Lao kip"],
  ["LBP", "Lebanese pound"],
  ["LKR", "Sri Lankan rupee"],
  ["LRD", "Liberian dollar"],
  ["LSL", "Lesotho loti"],
  ["LYD", "Libyan dinar"],
  ["MAD", "Moroccan dirham"],
  ["MDL", "Moldovan leu"],
  ["MGA", "Malagasy ariary"],
  ["MKD", "Macedonian denar"],
  ["MMK", "Myanmar kyat"],
  ["MNT", "Mongolian tögrög"],
  ["MOP", "Macanese pataca"],
  ["MRU", "Mauritanian ouguiya"],
  ["MUR", "Mauritian rupee"],
  ["MVR", "Maldivian rufiyaa"],
  ["MWK", "Malawian kwacha"],
  ["MXN", "Mexican peso"],
  ["MXV", "Mexican Unidad de Inversion (UDI) (funds code)"],
  ["MYR", "Malaysian ringgit"],
  ["MZN", "Mozambican metical"],
  ["NAD", "Namibian dollar"],
  ["NGN", "Nigerian naira"],
  ["NIO", "Nicaraguan córdoba"],
  ["NOK", "Norwegian krone"],
  ["NPR", "Nepalese rupee"],
  ["NZD", "New Zealand dollar"],
  ["OMR", "Omani rial"],
  ["PAB", "Panamanian balboa"],
  ["PEN", "Peruvian sol"],
  ["PGK", "Papua New Guinean kina"],
  ["PHP", "Philippine peso"],
  ["PKR", "Pakistani rupee"],
  ["PLN", "Polish złoty"],
  ["PYG", "Paraguayan guaraní"],
  ["QAR", "Qatari riyal"],
  ["RON", "Romanian leu"],
  ["RSD", "Serbian dinar"],
  ["RUB", "Russian ruble"],
  ["RWF", "Rwandan franc"],
  ["SAR", "Saudi riyal"],
  ["SBD", "Solomon Islands dollar"],
  ["SCR", "Seychelles rupee"],
  ["SDG", "Sudanese pound"],
  ["SEK", "Swedish krona"],
  ["SGD", "Singapore dollar"],
  ["SHP", "Saint Helena pound"],
  ["SLE", "Sierra Leonean leone"],
  ["SOS", "Somalian shilling"],
  ["SRD", "Surinamese dollar"],
  ["SSP", "South Sudanese pound"],
  ["STN", "São Tomé and Príncipe dobra"],
  ["SVC", "Salvadoran colón"],
  ["SYP", "Syrian pound"],
  ["SZL", "Swazi lilangeni"],
  ["THB", "Thai baht"],
  ["TJS", "Tajikistani somoni"],
  ["TMT", "Turkmenistan manat"],
  ["TND", "Tunisian dinar"],
  ["TOP", "Tongan paʻanga"],
  ["TRY", "Turkish lira"],
  ["TTD", "Trinidad and Tobago dollar"],
  ["TWD", "New Taiwan dollar"],
  ["TZS", "Tanzanian shilling"],
  ["UAH", "Ukrainian hryvnia"],
  ["UGX", "Ugandan shilling"],
  ["USD", "United States dollar"],
  ["USN", "United States dollar (next day) (funds code)"],
  ["UYI", "Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)"],
  ["UYU", "Uruguayan peso"],
  ["UYW", "Unidad previsional"],
  ["UZS", "Uzbekistani sum"],
  ["VED", "Venezuelan digital bolívar"],
  ["VES", "Venezuelan sovereign bolívar"],
  ["VND", "Vietnamese đồng"],
  ["VUV", "Vanuatu vatu"],
  ["WST", "Samoan tala"],
  ["XAF", "CFA franc BEAC"],
  ["XAG", "Silver (one troy ounce)"],
  ["XAU", "Gold (one troy ounce)"],
  ["XBA", "European Composite Unit (EURCO) (bond market unit)"],
  ["XBB", "European Monetary Unit (E.M.U.-6) (bond market unit)"],
  ["XBC", "European Unit of Account 9 (E.U.A.-9) (bond market unit)"],
  ["XBD", "European Unit of Account 17 (E.U.A.-17) (bond market unit)"],
  ["XCD", "East Caribbean dollar"],
  ["XDR", "Special drawing rights"],
  ["XOF", "CFA franc BCEAO"],
  ["XPD", "Palladium (one troy ounce)"],
  ["XPF", "CFP franc (franc Pacifique)"],
  ["XPT", "Platinum (one troy ounce)"],
  ["XSU", "SUCRE"],
  ["XTS", "Code reserved for testing"],
  ["XTS", "Code reserved for testing"],
  ["XUA", "ADB Unit of Account"],
  ["XXX", "No currency"],
  ["YER", "Yemeni rial"],
  ["ZAR", "South African rand"],
  ["ZMW", "Zambian kwacha"],
  ["ZWG", "Zimbabwe Gold"],
  ["ZWL", "	Zimbabwean dollar (fifth)"],
]

export type ISO_4217_CURRENCY_CODE = typeof ISO_4217_CURRENCY_CODES[number][0];

export const LOCALES: [BlendinLocaleCode, string, string, string[]][] = [
  ["en", "English", "English", ["one", "other"]],
  ["en-US", "English (United States)", "English (United States)", ["one", "other"]],
  ["en-GB", "English (Great Britain)", "English (Great Britain)", ["one", "other"]],
  ["en-CA", "English (Canada)", "English (Canada)", ["one", "other"]],
  ["en-AU", "English (Australia)", "English (Australia)", ["one", "other"]],
  ["en-NZ", "English (New Zealand)", "English (New Zealand)", ["one", "other"]],
  ["en-IE", "English (Ireland)", "English (Ireland)", ["one", "other"]],
  ["en-ZA", "English (South Africa)", "English (South Africa)", ["one", "other"]],
  ["zh", "Chinese", "中文", ["other"]],
  ["zh-CN", "Chinese (China)", "中文 (中国)", ["other"]],
  ["zh-TW", "Chinese (Taiwan)", "中文 (台灣)", ["other"]],
  ["zh-SG", "Chinese (Singapore)", "中文 (新加坡)", ["other"]],
  ["zh-MY", "Chinese (Malaysia)", "中文 (马来西亚)", ["other"]],
  ["hi", "Hindi", "हिन्दी", ["one", "other"]],
  ["es", "Spanish", "Español", ["one", "other"]],
  ["es-ES", "Spanish (Spain)", "Español (España)", ["one", "other"]],
  ["es-MX", "Spanish (Mexico)", "Español (México)", ["one", "other"]],
  ["es-CO", "Spanish (Colombia)", "Español (Colombia)", ["one", "other"]],
  ["es-AR", "Spanish (Argentina)", "Español (Argentina)", ["one", "other"]],
  ["es-PE", "Spanish (Peru)", "Español (Perú)", ["one", "other"]],
  ["es-VE", "Spanish (Venezuela)", "Español (Venezuela)", ["one", "other"]],
  ["es-CL", "Spanish (Chile)", "Español (Chile)", ["one", "other"]],
  ["ar", "Arabic", "العربية", ["one", "two", "few", "many", "other"]],
  ["ar-EG", "Arabic (Egypt)", "العربية (مصر)", ["one", "two", "few", "many", "other"]],
  ["ar-SA", "Arabic (Saudi Arabia)", "العربية (السعودية)", ["one", "two", "few", "many", "other"]],
  ["ar-IQ", "Arabic (Iraq)", "العربية (العراق)", ["one", "two", "few", "many", "other"]],
  ["ar-SY", "Arabic (Syria)", "العربية (سوريا)", ["one", "two", "few", "many", "other"]],
  ["ar-MA", "Arabic (Morocco)", "العربية (المغرب)", ["one", "two", "few", "many", "other"]],
  ["ar-DZ", "Arabic (Algeria)", "العربية (الجزائر)", ["one", "two", "few", "many", "other"]],
  ["bn", "Bengali", "বাংলা", ["one", "other"]],
  ["bn-BD", "Bengali (Bangladesh)", "বাংলা (বাংলাদেশ)", ["one", "other"]],
  ["bn-IN", "Bengali (India)", "বাংলা (ভারত)", ["one", "other"]],
  ["pt", "Portuguese", "Português", ["one", "other"]],
  ["pt-BR", "Portuguese (Brazil)", "Português (Brasil)", ["one", "other"]],
  ["pt-PT", "Portuguese (Portugal)", "Português (Portugal)", ["one", "other"]],
  ["pt-MZ", "Portuguese (Mozambique)", "Português (Moçambique)", ["one", "other"]],
  ["pt-AO", "Portuguese (Angola)", "Português (Angola)", ["one", "other"]],
  ["ru", "Russian", "Русский", ["one", "few", "many", "other"]],
  ["ru-RU", "Russian (Russia)", "Русский (Россия)", ["one", "few", "many", "other"]],
  ["ru-BY", "Russian (Belarus)", "Русский (Беларусь)", ["one", "few", "many", "other"]],
  ["ru-KZ", "Russian (Kazakhstan)", "Русский (Казахстан)", ["one", "few", "many", "other"]],
  ["ru-UA", "Russian (Ukraine)", "Русский (Украина)", ["one", "few", "many", "other"]],
  ["ja", "Japanese", "日本語", ["other"]],
  ["pa", "Punjabi", "ਪੰਜਾਬੀ", ["one", "other"]],
  ["pa-IN", "Punjabi (India)", "ਪੰਜਾਬੀ (ਭਾਰਤ)", ["one", "other"]],
  ["pa-PK", "Punjabi (Pakistan)", "پنجابی (پاکستان)", ["one", "other"]],
  ["mr", "Marathi", "मराठी", ["one", "other"]],
  ["jv", "Javanese", "ꦧꦱꦗꦮ", ["other"]],
  ["fa", "Persian", "فارسی", ["one", "other"]],
  ["fa-IR", "Persian (Iran)", "فارسی (ایران)", ["one", "other"]],
  ["fa-AF", "Persian (Afghanistan)", "فارسی (افغانستان)", ["one", "other"]],
  ["fr", "French", "Français", ["one", "other"]],
  ["fr-FR", "French (France)", "Français (France)", ["one", "other"]],
  ["fr-CA", "French (Canada)", "Français (Canada)", ["one", "other"]],
  ["fr-BE", "French (Belgium)", "Français (Belgique)", ["one", "other"]],
  ["fr-CH", "French (Switzerland)", "Français (Suisse)", ["one", "other"]],
  ["fr-MG", "French (Madagascar)", "Français (Madagascar)", ["one", "other"]],
  ["fr-CM", "French (Cameroon)", "Français (Cameroun)", ["one", "other"]],
  ["ha", "Hausa", "Hausa", ["one", "other"]],
  ["ha-NG", "Hausa (Nigeria)", "Hausa (Nigeria)", ["one", "other"]],
  ["ha-NE", "Hausa (Niger)", "Hausa (Niger)", ["one", "other"]],
  ["ko", "Korean", "한국어", ["other"]],
  ["ko-KR", "Korean (South Korea)", "한국어 (대한민국)", ["other"]],
  ["ko-KP", "Korean (North Korea)", "한국어 (조선민주주의인민공화국)", ["other"]],
  ["de", "German", "Deutsch", ["one", "other"]],
  ["de-DE", "German (Germany)", "Deutsch (Deutschland)", ["one", "other"]],
  ["de-AT", "German (Austria)", "Deutsch (Österreich)", ["one", "other"]],
  ["de-CH", "German (Switzerland)", "Deutsch (Schweiz)", ["one", "other"]],
  ["vi", "Vietnamese", "Tiếng Việt", ["other"]],
  ["ta", "Tamil", "தமிழ்", ["one", "other"]],
  ["ta-IN", "Tamil (India)", "தமிழ் (இந்தியா)", ["one", "other"]],
  ["ta-LK", "Tamil (Sri Lanka)", "தமிழ் (இலங்கை)", ["one", "other"]],
  ["ta-SG", "Tamil (Singapore)", "தமிழ் (சிங்கப்பூர்)", ["one", "other"]],
  ["te", "Telugu", "తెలుగు", ["one", "other"]],
  ["tr", "Turkish", "Türkçe", ["one", "other"]],
  ["tr-TR", "Turkish (Turkey)", "Türkçe (Türkiye)", ["one", "other"]],
  ["tr-CY", "Turkish (Cyprus)", "Türkçe (Kıbrıs)", ["one", "other"]],
  ["ur", "Urdu", "اردو", ["one", "other"]],
  ["ur-PK", "Urdu (Pakistan)", "اردو (پاکستان)", ["one", "other"]],
  ["ur-IN", "Urdu (India)", "اردو (بھارت)", ["one", "other"]],
  ["it", "Italian", "Italiano", ["one", "other"]],
  ["it-IT", "Italian (Italy)", "Italiano (Italia)", ["one", "other"]],
  ["it-CH", "Italian (Switzerland)", "Italiano (Svizzera)", ["one", "other"]],
  ["gu", "Gujarati", "ગુજરાતી", ["one", "other"]],
  ["ps", "Pashto", "پښتو", ["one", "other"]],
  ["ps-AF", "Pashto (Afghanistan)", "پښتو (افغانستان)", ["one", "other"]],
  ["ps-PK", "Pashto (Pakistan)", "پښتو (پاکستان)", ["one", "other"]],
  ["ig", "Igbo", "Igbo", ["one", "other"]],
  ["pl", "Polish", "Polski", ["one", "few", "many", "other"]],
  ["kn", "Kannada", "ಕನ್ನಡ", ["one", "other"]],
  ["id", "Indonesian", "Bahasa Indonesia", ["other"]],
  ["su", "Sundanese", "Basa Sunda", ["other"]],
  ["or", "Oriya", "ଓଡ଼ିଆ", ["one", "other"]],
  ["th", "Thai", "ไทย", ["other"]],
  ["ml", "Malayalam", "മലയാളം", ["one", "other"]],
  ["am", "Amharic", "አማርኛ", ["one", "other"]],
  ["az", "Azerbaijani", "Azərbaycan dili", ["one", "other"]],
  ["my", "Burmese", "ဗမာစာ", ["other"]],
  ["uk", "Ukrainian", "Українська", ["one", "few", "many", "other"]],
  ["uz", "Uzbek", "Oʻzbekcha", ["one", "other"]],
  ["ku", "Kurdish", "Kurdî", ["one", "other"]],
  ["ku-IQ", "Kurdish (Iraq)", "Kurdî (عێراق)", ["one", "other"]],
  ["ku-TR", "Kurdish (Turkey)", "Kurdî (Tirkiye)", ["one", "other"]],
  ["ku-IR", "Kurdish (Iran)", "Kurdî (Îran)", ["one", "other"]],
  ["ku-SY", "Kurdish (Syria)", "Kurdî (Sûriyê)", ["one", "other"]],
  ["tl", "Tagalog", "Tagalog", ["one", "other"]],
  ["zu", "Zulu", "isiZulu", ["one", "other"]],
  ["ff", "Fulah", "Pulaar", ["one", "other"]],
  ["ff-SN", "Fulah (Senegal)", "Pulaar (Senegaal)", ["one", "other"]],
  ["ff-GM", "Fulah (Gambia)", "Pulaar (Gambia)", ["one", "other"]],
  ["ff-ML", "Fulah (Mali)", "Pulaar (Mali)", ["one", "other"]],
  ["ff-NE", "Fulah (Niger)", "Pulaar (Nijer)", ["one", "other"]],
  ["mg", "Malagasy", "Malagasy", ["one", "other"]],
  ["om", "Oromo", "Afaan Oromoo", ["one", "other"]],
  ["ro", "Romanian", "Română", ["one", "other"]],
  ["ro-RO", "Romanian (Romania)", "Română (România)", ["one", "other"]],
  ["ro-MD", "Romanian (Moldova)", "Română (Moldova)", ["one", "other"]],
  ["sd", "Sindhi", "سنڌي", ["one", "other"]],
  ["sd-PK", "Sindhi (Pakistan)", "سنڌي (پاڪستان)", ["one", "other"]],
  ["sd-IN", "Sindhi (India)", "सिन्धी (भारत)", ["one", "other"]],
  ["as", "Assamese", "অসমীয়া", ["one", "other"]],
  ["nl", "Dutch", "Nederlands", ["one", "other"]],
  ["nl-NL", "Dutch (Netherlands)", "Nederlands (Nederland)", ["one", "other"]],
  ["nl-BE", "Dutch (Belgium)", "Nederlands (België)", ["one", "other"]],
  ["nl-SR", "Dutch (Suriname)", "Nederlands (Suriname)", ["one", "other"]],
  ["ms", "Malay", "Bahasa Melayu", ["other"]],
  ["ms-MY", "Malay (Malaysia)", "Bahasa Melayu (Malaysia)", ["other"]],
  ["ms-SG", "Malay (Singapore)", "Bahasa Melayu (Singapura)", ["other"]],
  ["ms-BN", "Malay (Brunei)", "Bahasa Melayu (Brunei)", ["other"]],
  ["yo", "Yoruba", "Èdè Yorùbá", ["one", "other"]],
  ["yo-NG", "Yoruba (Nigeria)", "Èdè Yorùbá (Nigeria)", ["one", "other"]],
  ["yo-BJ", "Yoruba (Benin)", "Èdè Yorùbá (Bẹ̀nẹ̀)", ["one", "other"]],
  ["xh", "Xhosa", "isiXhosa", ["one", "other"]],
  ["km", "Central Khmer", "ខ្មែរ", ["other"]],
  ["ne", "Nepali", "नेपाली", ["one", "other"]],
  ["si", "Sinhala", "සිංහල", ["one", "other"]],
  ["so", "Somali", "Soomaali", ["one", "other"]],
  ["so-SO", "Somali (Somalia)", "Soomaali (Soomaaliya)", ["one", "other"]],
  ["so-DJ", "Somali (Djibouti)", "Soomaali (Jabuuti)", ["one", "other"]],
  ["sw", "Swahili", "Kiswahili", ["one", "other"]],
  ["sw-KE", "Swahili (Kenya)", "Kiswahili (Kenya)", ["one", "other"]],
  ["sw-TZ", "Swahili (Tanzania)", "Kiswahili (Tanzania)", ["one", "other"]],
  ["sw-UG", "Swahili (Uganda)", "Kiswahili (Uganda)", ["one", "other"]],
  ["za", "Zhuang", "Cuengh", ["other"]],
  ["bm", "Bambara", "Bamanankan", ["other"]],
  ["el", "Greek", "Ελληνικά", ["one", "other"]],
  ["el-GR", "Greek (Greece)", "Ελληνικά (Ελλάδα)", ["one", "other"]],
  ["el-CY", "Greek (Cyprus)", "Ελληνικά (Κύπρος)", ["one", "other"]],
  ["hu", "Hungarian", "Magyar", ["one", "other"]],
  ["ht", "Haitian", "Kreyòl Ayisyen", ["one", "other"]],
  ["kk", "Kazakh", "қазақ тілі", ["one", "other"]],
  ["ny", "Chichewa", "Chichewa", ["one", "other"]],
  ["rn", "Rundi", "Ikirundi", ["one", "other"]],
  ["rw", "Kinyarwanda", "Ikinyarwanda", ["one", "other"]],
  ["ak", "Akan", "Akan", ["one", "other"]],
  ["cs", "Czech", "Čeština", ["one", "few", "many", "other"]],
  ["ca", "Catalan", "Català", ["one", "other"]],
  ["ln", "Lingala", "Lingála", ["one", "other"]],
  ["ln-CD", "Lingala (Democratic Republic of the Congo)", "Lingála (Repibiki ya Kongó Demokratiki)", ["one", "other"]],
  ["ln-CG", "Lingala (Congo)", "Lingála (Kongo)", ["one", "other"]],
  ["sv", "Swedish", "Svenska", ["one", "other"]],
  ["sv-SE", "Swedish (Sweden)", "Svenska (Sverige)", ["one", "other"]],
  ["sv-FI", "Swedish (Finland)", "Svenska (Finland)", ["one", "other"]],
  ["ug", "Uighur", "ئۇيغۇرچە", ["one", "other"]],
  ["he", "Hebrew", "עברית", ["one", "other"]],
  ["sr", "Serbian", "Српски", ["one", "few", "many", "other"]],
  ["sr-RS", "Serbian (Serbia)", "Српски (Србија)", ["one", "few", "many", "other"]],
  ["sr-BA", "Serbian (Bosnia and Herzegovina)", "Српски (Босна и Херцеговина)", ["one", "few", "many", "other"]],
  ["ti", "Tigrinya", "ትግርኛ", ["one", "other"]],
  ["ti-ET", "Tigrinya (Ethiopia)", "ትግርኛ (ኢትዮጵያ)", ["one", "other"]],
  ["ti-ER", "Tigrinya (Eritrea)", "ትግርኛ (ኤርትራ)", ["one", "other"]],
  ["tw", "Twi", "Twi", ["one", "other"]],
  ["tn", "Tswana", "Setswana", ["one", "other"]],
  ["bg", "Bulgarian", "Български", ["one", "other"]],
  ["qu", "Quechua", "Runasimi", ["one", "other"]],
  ["qu-PE", "Quechua (Peru)", "Runasimi (Piruw)", ["one", "other"]],
  ["qu-BO", "Quechua (Bolivia)", "Runasimi (Buliwya)", ["one", "other"]],
  ["qu-EC", "Quechua (Ecuador)", "Runasimi (Ikwadur)", ["one", "other"]],
  ["tg", "Tajik", "тоҷикӣ", ["one", "other"]],
  ["be", "Belarusian", "Беларуская", ["one", "few", "many", "other"]],
  ["sn", "Shona", "chiShona", ["one", "other"]],
  ["sq", "Albanian", "Shqip", ["one", "other"]],
  ["sq-AL", "Albanian (Albania)", "Shqip (Shqipëri)", ["one", "other"]],
  ["sq-XK", "Albanian (Kosovo)", "Shqip (Kosovë)", ["one", "other"]],
  ["af", "Afrikaans", "Afrikaans", ["one", "other"]],
  ["af-ZA", "Afrikaans (South Africa)", "Afrikaans (Suid-Afrika)", ["one", "other"]],
  ["af-NA", "Afrikaans (Namibia)", "Afrikaans (Namibië)", ["one", "other"]],
  ["ee", "Ewe", "Eʋegbe", ["one", "other"]],
  ["ee-GH", "Ewe (Ghana)", "Eʋegbe (Ghana)", ["one", "other"]],
  ["ee-TG", "Ewe (Togo)", "Eʋegbe (Togo)", ["one", "other"]],
  ["kg", "Kongo", "Kikongo", ["one", "other"]],
  ["ks", "Kashmiri", "कॉशुर", ["one", "other"]],
  ["lg", "Ganda", "Luganda", ["one", "other"]],
  ["lo", "Lao", "ລາວ", ["other"]],
  ["tk", "Turkmen", "Türkmençe", ["one", "other"]],
  ["hy", "Armenian", "Հայերեն", ["one", "other"]],
  ["ki", "Kikuyu", "Gĩkũyũ", ["one", "other"]],
  ["st", "Southern Sotho", "Sesotho", ["one", "other"]],
  ["hr", "Croatian", "Hrvatski", ["one", "few", "many", "other"]],
  ["hr-HR", "Croatian (Croatia)", "Hrvatski (Hrvatska)", ["one", "few", "many", "other"]],
  ["hr-BA", "Croatian (Bosnia and Herzegovina)", "Hrvatski (Bosna i Hercegovina)", ["one", "few", "many", "other"]],
  ["da", "Danish", "Dansk", ["one", "other"]],
  ["sk", "Slovak", "Slovenčina", ["one", "few", "many", "other"]],
  ["fi", "Finnish", "Suomi", ["one", "other"]],
  ["nb", "Norwegian Bokmål", "Bokmål", ["one", "other"]],
  ["no", "Norwegian", "Norsk", ["one", "other"]],
  ["tt", "Tatar", "татар теле", ["one", "other"]],
  ["mn", "Mongolian", "Монгол", ["one", "other"]],
  ["wo", "Wolof", "Wolof", ["one", "other"]],
  ["gn", "Guarani", "Avañe'ẽ", ["one", "other"]],
  ["ky", "Kirghiz", "кыргыз тили", ["one", "other"]],
  ["kr", "Kanuri", "Kanuri", ["one", "other"]],
  ["ka", "Georgian", "ქართული", ["other"]],
  ["ts", "Tsonga", "Xitsonga", ["one", "other"]],
  ["lt", "Lithuanian", "Lietuvių", ["one", "few", "many", "other"]],
  ["mk", "Macedonian", "Македонски", ["one", "other"]],
  ["sl", "Slovenian", "Slovenščina", ["one", "two", "few", "other"]],
  ["gl", "Galician", "Galego", ["one", "other"]],
  ["ss", "Swati", "siSwati", ["one", "other"]],
  ["ay", "Aymara", "Aymar aru", ["other"]],
  ["ay-BO", "Aymara (Bolivia)", "Aymar aru (Buliwya)", ["other"]],
  ["ay-PE", "Aymara (Peru)", "Aymar aru (Piruw)", ["other"]],
  ["bs", "Bosnian", "Bosanski", ["one", "few", "many", "other"]],
  ["ii", "Sichuan Yi", "ꆈꌠꉙ", ["other"]],
  ["eo", "Esperanto", "Esperanto", ["one", "other"]],
  ["nd", "North Ndebele", "isiNdebele", ["one", "other"]],
  ["oc", "Occitan", "Occitan", ["one", "other"]],
  ["ve", "Venda", "Tshivenda", ["one", "other"]],
  ["li", "Limburgan", "Limburgs", ["one", "other"]],
  ["li-NL", "Limburgan (Netherlands)", "Limburgs (Nederland)", ["one", "other"]],
  ["li-BE", "Limburgan (Belgium)", "Limburgs (België)", ["one", "other"]],
  ["aa", "Afar", "Qafár af", ["one", "other"]],
  ["aa-ET", "Afar (Ethiopia)", "Qafár af (Ethiopia)", ["one", "other"]],
  ["aa-DJ", "Afar (Djibouti)", "Qafár af (Djibouti)", ["one", "other"]],
  ["ce", "Chechen", "Нохчийн", ["one", "other"]],
  ["lu", "Luba-Katanga", "Tshiluba", ["one", "other"]],
  ["lv", "Latvian", "Latviešu", ["one", "other"]],
  ["sc", "Sardinian", "Sardu", ["one", "other"]],
  ["yi", "Yiddish", "ייִדיש", ["one", "other"]],
  ["yi-IL", "Yiddish (Israel)", "ייִדיש (ישראל)", ["one", "other"]],
  ["yi-US", "Yiddish (United States)", "ייִדיש (פֿאַראייניקטע שטאַטן)", ["one", "other"]],
  ["ba", "Bashkir", "Башҡорт теле", ["one", "other"]],
  ["bo", "Tibetan", "བོད་ཡིག", ["other"]],
  ["ga", "Irish", "Gaeilge", ["one", "two", "few", "many", "other"]],
  ["cv", "Chuvash", "Чӑвашла", ["one", "other"]],
  ["et", "Estonian", "Eesti", ["one", "other"]],
  ["nr", "South Ndebele", "isiNdebele", ["one", "other"]],
  ["ng", "Ndonga", "Oshindonga", ["one", "other"]],
  ["av", "Avaric", "МагӀарул мацӀ", ["one", "other"]],
  ["eu", "Basque", "Euskara", ["one", "other"]],
  ["nn", "Norwegian Nynorsk", "Nynorsk", ["one", "other"]],
  ["cy", "Welsh", "Cymraeg", ["one", "two", "few", "many", "other"]],
  ["os", "Ossetian", "Ирон", ["one", "other"]],
  ["wa", "Walloon", "Walon", ["one", "other"]],
  ["sg", "Sango", "Sängö", ["one", "other"]],
  ["mt", "Maltese", "Malti", ["one", "few", "many", "other"]],
  ["sm", "Samoan", "Gagana Samoa", ["one", "other"]],
  ["fy", "Western Frisian", "Frysk", ["one", "other"]],
  ["lb", "Luxembourgish", "Lëtzebuergesch", ["one", "other"]],
  ["dv", "Divehi", "ދިވެހި", ["one", "other"]],
  ["fj", "Fijian", "Na Vosa Vakaviti", ["one", "other"]],
  ["is", "Icelandic", "Íslenska", ["one", "other"]],
  ["hz", "Herero", "Otjiherero", ["one", "other"]],
  ["kj", "Kuanyama", "Kuanyama", ["one", "other"]],
  ["kv", "Komi", "Коми кыв", ["one", "other"]],
  ["br", "Breton", "Brezhoneg", ["one", "two", "few", "many", "other"]],
  ["dz", "Dzongkha", "རྫོང་ཁ", ["other"]],
  ["ab", "Abkhazian", "Аҧсуа", ["one", "other"]],
  ["to", "Tonga", "lea faka-Tonga", ["one", "other"]],
  ["nv", "Navajo", "Diné Bizaad", ["one", "other"]],
  ["mi", "Maori", "Te Reo Māori", ["other"]],
  ["co", "Corsican", "Corsu", ["one", "other"]],
  ["ty", "Tahitian", "Reo Tahiti", ["one", "other"]],
  ["ho", "Hiri Motu", "Hiri Motu", ["one", "other"]],
  ["cr", "Cree", "ᓀᐦᐃᔭᐍᐏᐣ", ["one", "other"]],
  ["fo", "Faroese", "Føroyskt", ["one", "other"]],
  ["ch", "Chamorro", "Chamoru", ["one", "other"]],
  ["gd", "Gaelic", "Gàidhlig", ["one", "two", "few", "other"]],
  ["rm", "Romansh", "Rumantsch", ["one", "other"]],
  ["mh", "Marshallese", "Kajin M̧ajeļ", ["one", "other"]],
  ["kl", "Kalaallisut", "Kalaallisut", ["other"]],
  ["oj", "Ojibwa", "ᐊᓂᔑᓈᐯᒧᐎᓐ", ["one", "other"]],
  ["iu", "Inuktitut", "ᐃᓄᒃᑎᑐᑦ", ["one", "two", "other"]],
  ["se", "Northern Sami", "Davvisámegiella", ["one", "two", "other"]],
  ["sa", "Sanskrit", "संस्कृतम्", ["one", "other"]],
  ["an", "Aragonese", "Aragonés", ["one", "other"]],
  ["bi", "Bislama", "Bislama", ["one", "other"]],
  ["na", "Nauru", "Dorerin Naoero", ["one", "other"]],
  ["ik", "Inupiaq", "Iñupiatun", ["one", "two", "other"]],
  ["gv", "Manx", "Gaelg", ["one", "two", "few", "other"]],
  ["kw", "Cornish", "Kernowek", ["one", "two", "few", "other"]],
  ["io", "Ido", "Ido", ["one", "other"]],
  ["ae", "Avestan", "Avesta", ["other"]],
  ["cu", "Church Slavonic", "Церковнославянский", ["one", "few", "many", "other"]],
  ["ia", "Interlingua", "Interlingua", ["one", "other"]],
  ["ie", "Interlingue", "Interlingue", ["one", "other"]],
  ["la", "Latin", "Latina", ["one", "other"]],
  ["pi", "Pali", "Pāli", ["other"]],
  ["vo", "Volapük", "Volapük", ["one", "other"]]
];

export const SUPPORTED_LOCALE_CODES: BlendinLocaleCode[] = LOCALES.map(x => x[0]);

export const DEFAULT_FLAGS: Record<ISO_639_LANGUAGE_CODE, ISO_3166_COUNTRY_CODE> = {
  "en": "US",
  "zh": "CN",
  "hi": "IN",
  "es": "ES",
  "ar": "SA",
  "bn": "BD",
  "pt": "PT",
  "ru": "RU",
  "ja": "JP",
  "pa": "IN",
  "mr": "IN",
  "jv": "ID",
  "fa": "IR",
  "fr": "FR",
  "ha": "NG",
  "ko": "KR",
  "de": "DE",
  "vi": "VN",
  "ta": "LK",
  "te": "IN",
  "tr": "TR",
  "ur": "PK",
  "it": "IT",
  "gu": "IN",
  "ps": "AF",
  "ig": "NG",
  "pl": "PL",
  "kn": "IN",
  "id": "ID",
  "su": "ID",
  "or": "IN",
  "th": "TH",
  "ml": "IN",
  "am": "ET",
  "az": "AZ",
  "my": "MM",
  "uk": "UA",
  "uz": "UZ",
  "ku": "IQ",
  "tl": "PH",
  "zu": "ZA",
  "ff": "SN",
  "mg": "MG",
  "om": "ET",
  "ro": "RO",
  "sd": "PK",
  "as": "IN",
  "nl": "NL",
  "ms": "BN",
  "yo": "NG",
  "xh": "ZA",
  "km": "KH",
  "ne": "NP",
  "si": "LK",
  "so": "SO",
  "sw": "KE",
  "za": "CN",
  "bm": "ML",
  "el": "GR",
  "hu": "HU",
  "ht": "HT",
  "kk": "KZ",
  "ny": "MW",
  "rn": "BI",
  "rw": "RW",
  "ak": "GH",
  "cs": "CZ",
  "ca": "AD",
  "ln": "CD",
  "sv": "SE",
  "ug": "CN",
  "he": "IL",
  "sr": "RS",
  "ti": "ET",
  "tw": "GH",
  "tn": "BW",
  "bg": "BG",
  "qu": "PE",
  "tg": "TJ",
  "be": "BY",
  "sn": "ZW",
  "sq": "AL",
  "af": "ZA",
  "ee": "GH",
  "kg": "CD",
  "ks": "IN",
  "lg": "UG",
  "lo": "LA",
  "tk": "TM",
  "hy": "AM",
  "ki": "KE",
  "st": "LS",
  "hr": "HR",
  "da": "DK",
  "sk": "SK",
  "fi": "FI",
  "nb": "NO",
  "no": "NO",
  "tt": "RU",
  "mn": "MN",
  "wo": "SN",
  "gn": "PY",
  "ky": "KG",
  "kr": "NG",
  "ka": "GE",
  "ts": "SZ",
  "lt": "LT",
  "mk": "MK",
  "sl": "SI",
  "gl": "ES",
  "ss": "SZ",
  "ay": "BO",
  "bs": "BA",
  "ii": "CN",
  "eo": "CH",
  "nd": "ZW",
  "oc": "FR",
  "ve": "ZA",
  "li": "NL",
  "aa": "ET",
  "ce": "RU",
  "lu": "CD",
  "lv": "LV",
  "sc": "IT",
  "yi": "IL",
  "ba": "RU",
  "bo": "CN",
  "ga": "IE",
  "cv": "RU",
  "et": "EE",
  "nr": "ZA",
  "ng": "NA",
  "av": "RU",
  "eu": "ES",
  "nn": "NO",
  "cy": "GB",
  "os": "RU",
  "wa": "BE",
  "sg": "CF",
  "mt": "MT",
  "sm": "WS",
  "fy": "NL",
  "lb": "LU",
  "dv": "MV",
  "fj": "FJ",
  "is": "IS",
  "hz": "NA",
  "kj": "NA",
  "kv": "RU",
  "br": "FR",
  "dz": "BT",
  "ab": "RU",
  "to": "TO",
  "nv": "US",
  "mi": "NZ",
  "co": "FR",
  "ty": "FR",
  "ho": "PG",
  "cr": "CA",
  "fo": "DK",
  "ch": "GU",
  "gd": "IE",
  "rm": "CH",
  "mh": "MH",
  "kl": "DK",
  "oj": "CA",
  "iu": "CA",
  "se": "NO",
  "sa": "IN",
  "an": "ES",
  "bi": "VU",
  "na": "NR",
  "ik": "US",
  "gv": "GB",
  "kw": "GB",
  "io": "PG",
  "ae": "IR",
  "cu": "BY",
  "ia": "CH",
  "ie": "CH",
  "la": "IT",
  "pi": "IN",
  "vo": "CH"
};
